name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      
      - name: Checkout QS CFN
        uses: actions/checkout@v2
        with:
          repository: 'aws-quickstart/qs-cfn-lint-rules'
          path: './qs-cfn-lint-rules'

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cd qs-cfn-lint-rules
          pip install -e .
          cd ..
          ls ./qs-cfn-lint-rules/qs_cfn_lint_rules/
          cfn-lint templates/* -a ./qs-cfn-lint-rules/qs_cfn_lint_rules/
